codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 2%

# Multiple coverage reports: AssemblyScript (WASM) and JavaScript (wrapper)
flag_management:
  individual_flags:
    - name: assemblyscript
      paths:
        - src/assembly/
      carryforward: true
    - name: javascript
      paths:
        - src/
      carryforward: true

# Ignore paths that shouldn't affect coverage
ignore:
  - "node_modules/**"
  - "src/types/**"
  - "src/assembly/test/**"
  - "test/**"
  - "examples/**"
  - "docs/**"
  - "util/**"
  - "dist/**"

# Comment configuration
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
